#ifndef __include_oracle_puppet_h
#define __include_oracle_puppet_h

#include <Arduino.h>
#include <AliceDefaultConfig.h>
#include <oracle_puppet.h>

#define ORACLE_PUPPET_MAX_NUM_DEFAULT ALICE_PAPILLON_CONFIG_SERVO_MAX_NUM_DEFAULT

#define ORACLE_PUPPET_SERVO1_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE
#define ORACLE_PUPPET_SERVO1_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE
#define ORACLE_PUPPET_SERVO1_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE
#define ORACLE_PUPPET_SERVO1_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO1_PIN

#define ORACLE_PUPPET_SERVO2_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE
#define ORACLE_PUPPET_SERVO2_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE
#define ORACLE_PUPPET_SERVO2_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE
#define ORACLE_PUPPET_SERVO2_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO2_PIN

#define ORACLE_PUPPET_SERVO3_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE
#define ORACLE_PUPPET_SERVO3_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE
#define ORACLE_PUPPET_SERVO3_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE
#define ORACLE_PUPPET_SERVO3_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO3_PIN

#define ORACLE_PUPPET_SERVO4_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE
#define ORACLE_PUPPET_SERVO4_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE
#define ORACLE_PUPPET_SERVO4_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE
#define ORACLE_PUPPET_SERVO4_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO4_PIN

#define ORACLE_PUPPET_SERVO5_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE
#define ORACLE_PUPPET_SERVO5_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE
#define ORACLE_PUPPET_SERVO5_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE
#define ORACLE_PUPPET_SERVO5_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO5_PIN

#define ORACLE_PUPPET_SERVO6_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE
#define ORACLE_PUPPET_SERVO6_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE
#define ORACLE_PUPPET_SERVO6_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE
#define ORACLE_PUPPET_SERVO6_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO6_PIN

#define ORACLE_PUPPET_SERVO7_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE
#define ORACLE_PUPPET_SERVO7_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE
#define ORACLE_PUPPET_SERVO7_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE
#define ORACLE_PUPPET_SERVO7_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO7_PIN

#define ORACLE_PUPPET_SERVO8_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE
#define ORACLE_PUPPET_SERVO8_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE
#define ORACLE_PUPPET_SERVO8_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE
#define ORACLE_PUPPET_SERVO8_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO8_PIN


#define ORACLE_PUPPET_NUM_BATCHS 4
#define ORACLE_PUPPET_NUM_FRAMES 96

typedef struct oracle_puppet_config_s {
    uint8_t *gpio_motors;
    bool *status_motors;
    uint8_t num_gpios;
} oracle_puppet_config_t;

typedef struct oracle_puppet_frames_s {
    int num_batchs;
    int batch_index;
    int num_frames;
    int frame_index;
    uint32_t **frame_positions;
    uint32_t *frame_delay;
    bool *frame_status;
} oracle_puppet_frames_t;

typedef struct oracle_puppet_context_s {
    /* servo */
    int angle_min;
    int angle_ini;
    int angle_max;
    int gpio_pin;
    int index;
    oracle_puppet_frames_t *frames;
    bool is_running;
    bool enable;
} oracle_puppet_context_t;



#endif /* #ifndef __include_oracle_puppet_h */