#ifndef __include_oracle_puppet_h
#define __include_oracle_puppet_h

#include <Arduino.h>
#include <AliceDefaultConfig.h>
#include <oracle_puppet.h>

#define ORACLE_PUPPET_MAX_NUM_DEFAULT ALICE_PAPILLON_CONFIG_SERVO_MAX_NUM_DEFAULT

#define ORACLE_PUPPET_SERVO1_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE
#define ORACLE_PUPPET_SERVO1_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE
#define ORACLE_PUPPET_SERVO1_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE
#define ORACLE_PUPPET_SERVO1_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO1_PIN

#define ORACLE_PUPPET_SERVO2_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE
#define ORACLE_PUPPET_SERVO2_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE
#define ORACLE_PUPPET_SERVO2_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE
#define ORACLE_PUPPET_SERVO2_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO2_PIN

#define ORACLE_PUPPET_SERVO3_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE
#define ORACLE_PUPPET_SERVO3_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE
#define ORACLE_PUPPET_SERVO3_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE
#define ORACLE_PUPPET_SERVO3_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO3_PIN

#define ORACLE_PUPPET_SERVO4_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE
#define ORACLE_PUPPET_SERVO4_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE
#define ORACLE_PUPPET_SERVO4_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE
#define ORACLE_PUPPET_SERVO4_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO4_PIN

#define ORACLE_PUPPET_SERVO5_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE
#define ORACLE_PUPPET_SERVO5_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE
#define ORACLE_PUPPET_SERVO5_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE
#define ORACLE_PUPPET_SERVO5_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO5_PIN

#define ORACLE_PUPPET_SERVO6_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE
#define ORACLE_PUPPET_SERVO6_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE
#define ORACLE_PUPPET_SERVO6_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE
#define ORACLE_PUPPET_SERVO6_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO6_PIN

#define ORACLE_PUPPET_SERVO7_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE
#define ORACLE_PUPPET_SERVO7_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE
#define ORACLE_PUPPET_SERVO7_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE
#define ORACLE_PUPPET_SERVO7_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO7_PIN

#define ORACLE_PUPPET_SERVO8_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE
#define ORACLE_PUPPET_SERVO8_MIN_ANGLE  ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE
#define ORACLE_PUPPET_SERVO8_MAX_ANGLE  ALICE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE
#define ORACLE_PUPPET_SERVO8_GPIO_PIN   ALICE_PAPILLON_CONFIG_SERVO8_PIN

#define ORACLE_PUPPET_NUM_BATCHS 4
#define ORACLE_PUPPET_NUM_FRAMES 256

typedef struct oracle_puppet_config_s {
    uint8_t *gpio_motors;
    bool *status_motors;
    uint8_t num_gpios;
} oracle_puppet_config_t;

typedef struct oracle_puppet_frame_s {
    char buffer[ORACLE_PUPPET_NUM_FRAMES];
    uint8_t index;
    bool in_use;
} oracle_puppet_frame_t;

typedef struct oracle_puppet_frames_s {
    oracle_puppet_frame_t frames[ORACLE_PUPPET_NUM_BATCHS];
    uint8_t running_index;
    uint8_t upload_index;
} oracle_puppet_frames_t;

typedef struct oracle_puppet_config_servo_s {
    uint16_t angle_min;
    uint16_t angle_ini;
    uint16_t angle_max;
    uint16_t gpio_pin;
} struct oracle_puppet_config_servo_t;

typedef struct oracle_pupper_state_servo_s {
    uint16_t angle;
    uint8_t is_running;
    uint8_t pad0;
} oracle_pupper_state_servo_t;

typedef struct oracle_puppet_context_s {
    /* servo */
    uint16_t index;
    uint8_t enable;
    uint8_t pad0;
    oracle_puppet_config_servo_t *config;
} oracle_puppet_context_t;

#endif /* #ifndef __include_oracle_puppet_h */