#ifndef __include_oracle_default_config_h
#define __include_oracle_default_config_h

/*****************************************************/
/****************** DEFAULT VALUES *******************/
/*****************************************************/

/* Network Configuration Variables */
#define ORACLE_WIFI_CONFIG_SSID_DEFAULT                  "AliceTestSSID"
#define ORACLE_WIFI_CONFIG_PWD_DEFAULT                   "AliceTestPWD"
#define ORACLE_WIFI_CONFIG_FIRST_DELAY_DEFAULT           1000
#define ORACLE_WIFI_CONFIG_TIMEOUT_DEFAULT               1000
#define ORACLE_WIFI_CONFIG_RETRY_DEFAULT                 1000

/* Esp32 Configuration Variables */
#define ORACLE_ESP32_CONFIG_NAME_DEFAULT                 "alice_ESP32_test_name"
#define ORACLE_ESP32_CONFIG_DELAY_DEFAULT                100

/* Leds Configuration Variables */
#define ORACLE_LEDS_CONFIG_NUM_LEDS_DEFAULT              30
#define ORACLE_LEDS_CONFIG_LED_PIN_DEFAULT               19
#define ORACLE_LEDS_CONFIG_COLOR_ORDER_DEFAULT           GRB
#define ORACLE_LEDS_CONFIG_LED_TYPE_DEFAULT              WS2812B
#define ORACLE_LEDS_CONFIG_MAX_BRIGHTNESS_DEFAULT        255
#define ORACLE_LEDS_CONFIG_MIN_CUBICWAVE_DEFAULT         50
#define ORACLE_LEDS_CONFIG_MAX_CUBICWAVE_DEFAULT         90
#define ORACLE_LEDS_CONFIG_FADE_AMOUNT_DEFAULT           5

/* HCSR04 Configuration Variables*/
#define ORACLE_HCSR04_CONFIG_ECHO_PIN_DEFAULT            18
#define ORACLE_HCSR04_CONFIG_TRIGGER_PIN_DEFAULT         5
#define ORACLE_HCSR04_CONFIG_MAX_DISTANCE_DEFAULT        50
#define ORACLE_HCSR04_CONFIG_EXPECTED_DISTANCE_DEFAULT   20
#define ORACLE_HCSR04_CONFIG_EXPECTED_DURATION_DEFAULT   4000
#define ORACLE_HCSR04_CONFIG_MAX_VALUE_DEFAULT           5000
#define ORACLE_HCSR04_CONFIG_REPEAT_DEFAULT              10
#define ORACLE_HCSR04_CONFIG_SPEED_OF_SOUND_DEFAULT      29.1

/* Papillon Configuration Variables */
#define ORACLE_PAPILLON_CONFIG_SERVO_MAX_NUM_DEFAULT     8
#define ORACLE_PAPILLON_CONFIG_SERVO_NUM_DEFAULT         1
#define ORACLE_PAPILLON_CONFIG_SERVO1_PIN_DEFAULT        5
#define ORACLE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE_DEFAULT 160
#define ORACLE_PAPILLON_CONFIG_SERVO1_ROUND_NUM_DEFAULT  1
#define ORACLE_PAPILLON_CONFIG_SERVO2_PIN_DEFAULT        6
#define ORACLE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO2_ROUND_NUM_DEFAULT  1
#define ORACLE_PAPILLON_CONFIG_SERVO3_PIN_DEFAULT        7
#define ORACLE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO3_ROUND_NUM_DEFAULT  1
#define ORACLE_PAPILLON_CONFIG_SERVO4_PIN_DEFAULT        8
#define ORACLE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO4_ROUND_NUM_DEFAULT  1
#define ORACLE_PAPILLON_CONFIG_SERVO5_PIN_DEFAULT        9
#define ORACLE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO5_ROUND_NUM_DEFAULT  1
#define ORACLE_PAPILLON_CONFIG_SERVO6_PIN_DEFAULT        10
#define ORACLE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO6_ROUND_NUM_DEFAULT  1
#define ORACLE_PAPILLON_CONFIG_SERVO7_PIN_DEFAULT        11
#define ORACLE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO7_ROUND_NUM_DEFAULT  1
#define ORACLE_PAPILLON_CONFIG_SERVO8_PIN_DEFAULT        12
#define ORACLE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE_DEFAULT  90
#define ORACLE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE_DEFAULT  160
#define ORACLE_PAPILLON_CONFIG_SERVO8_ROUND_NUM_DEFAULT  1

/* Parfum Configuration Variables */
#define ORACLE_PARFUM_CONFIG_ALWAYS_ON_DEFAULT           0
#define ORACLE_PARFUM_CONFIG_PIN_DEFAULT                 18
#define ORACLE_PARFUM_CONFIG_MAX_TIME_DEFAULT            10000

/* Define BUBBLE Configuration */
#define ORACLE_BUBBLE_CONFIG_ALWAYS_ON_DEFAULT           0
#define ORACLE_BUBBLE_CONFIG_STATE_PIN_DEFAULT           34
#define ORACLE_BUBBLE_CONFIG_ACTION_PIN_DEFAULT          12
#define ORACLE_BUBBLE_CONFIG_MAX_TIME_DEFAULT            10000
#define ORACLE_BUBBLE_CONFIG_STATE_THRESHOLD_DEFAULT     300

/* Define CHROMIE Configuration */

#define ORACLE_CHROMIE_CONFIG_SDA_PIN_DEFAULT            21
#define ORACLE_CHROMIE_CONFIG_SCL_PIN_DEFAULT            22
#define ORACLE_CHROMIE_CONFIG_MAX_REPEAT_DEFAULT         5
#define ORACLE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT        {0x00, 0x00, 0x00, 0x00}
#define ORACLE_CHROMIE_CONFIG_COLOR_RED_DEFAULT          ORACLE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ORACLE_CHROMIE_CONFIG_COLOR_GREEN_DEFAULT        ORACLE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ORACLE_CHROMIE_CONFIG_COLOR_BLUE_DEFAULT         ORACLE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ORACLE_CHROMIE_CONFIG_COLOR_YELLOW_DEFAULT       ORACLE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ORACLE_CHROMIE_CONFIG_COLOR_PURPLE_DEFAULT       ORACLE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ORACLE_CHROMIE_CONFIG_COLOR_PINK_DEFAULT         ORACLE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT

/* Define SMOCK Configuration */
#define ORACLE_SMOCK_CONFIG_ALWAYS_ON_DEFAULT            0
#define ORACLE_SMOCK_CONFIG_PIN_DEFAULT                  12
#define ORACLE_SMOCK_CONFIG_MAX_TIME_DEFAULT             10000
#define ORACLE_SMOCK_CONFIG_MAX_REPEAT_DEFAULT           10

/* Define RFID RC522 Configuration */
#define ORACLE_RC522_CONFIG_RST_PIN_DEFAULT               22
#define ORACLE_RC522_CONFIG_MISO_PIN_DEFAULT              19
#define ORACLE_RC522_CONFIG_MOSI_PIN_DEFAULT              23
#define ORACLE_RC522_CONFIG_SCK_PIN_DEFAULT               18
#define ORACLE_RC522_CONFIG_SDA_PIN_DEFAULT               5

/*****************************************************/
/************ SET VALUES IF NOT DEFINED **************/
/*****************************************************/

/* Network Config Variables */

#ifndef ORACLE_WIFI_CONFIG_SSID
#define ORACLE_WIFI_CONFIG_SSID ORACLE_WIFI_CONFIG_SSID_DEFAULT
#endif /* ORACLE_WIFI_CONFIG_SSID */

#ifndef ORACLE_WIFI_CONFIG_PWD
#define ORACLE_WIFI_CONFIG_PWD ORACLE_WIFI_CONFIG_PWD_DEFAULT
#endif /* ORACLE_WIFI_CONFIG_PWD */

#ifndef ORACLE_WIFI_CONFIG_MAC_ADDRESS
#define ORACLE_WIFI_CONFIG_MAC_ADDRESS ORACLE_WIFI_CONFIG_MAC_ADDRESS_DEFAULT
#endif /* ORACLE_WIFI_CONFIG_MAC_ADDRESS */

#ifndef ORACLE_WIFI_CONFIG_FIRST_DELAY
#define ORACLE_WIFI_CONFIG_FIRST_DELAY ORACLE_WIFI_CONFIG_FIRST_DELAY_DEFAULT
#endif /* ORACLE_WIFI_CONFIG_FIRST_DELAY */

#ifndef ORACLE_WIFI_CONFIG_TIMEOUT
#define ORACLE_WIFI_CONFIG_TIMEOUT ORACLE_WIFI_CONFIG_TIMEOUT_DEFAULT
#endif /* ORACLE_WIFI_CONFIG_TIMEOUT */

#ifndef ORACLE_WIFI_CONFIG_RETRY
#define ORACLE_WIFI_CONFIG_RETRY ORACLE_WIFI_CONFIG_RETRY_DEFAULT
#endif /* ORACLE_WIFI_CONFIG_RETRY */

#ifndef ORACLE_SERVER_CONFIG_PORT
#define ORACLE_SERVER_CONFIG_PORT ORACLE_SERVER_CONFIG_PORT_DEFAULT
#endif /* ORACLE_SERVER_CONFIG_PORT */

/* Esp32 Config Variables */

#ifndef ORACLE_ESP32_CONFIG_NAME
#define ORACLE_ESP32_CONFIG_NAME ORACLE_ESP32_CONFIG_NAME_DEFAULT
#endif /* ORACLE_ESP32_CONFIG_NAME */

#ifndef ORACLE_ESP32_CONFIG_DELAY
#define ORACLE_ESP32_CONFIG_DELAY ORACLE_ESP32_CONFIG_DELAY_DEFAULT
#endif /* ORACLE_ESP32_CONFIG_DELAY */

/* Leds Config Variables */

#ifndef ORACLE_LEDS_CONFIG_NUM_LEDS
#define ORACLE_LEDS_CONFIG_NUM_LEDS ORACLE_LEDS_CONFIG_NUM_LEDS_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_NUM_LEDS */

#ifndef ORACLE_LEDS_CONFIG_LED_PIN
#define ORACLE_LEDS_CONFIG_LED_PIN ORACLE_LEDS_CONFIG_LED_PIN_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_LED_PIN */

#ifndef ORACLE_LEDS_CONFIG_COLOR_ORDER
#define ORACLE_LEDS_CONFIG_COLOR_ORDER ORACLE_LEDS_CONFIG_COLOR_ORDER_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_COLOR_ORDER */

#ifndef ORACLE_LEDS_CONFIG_LED_TYPE
#define ORACLE_LEDS_CONFIG_LED_TYPE ORACLE_LEDS_CONFIG_LED_TYPE_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_LED_TYPE */

#ifndef ORACLE_LEDS_CONFIG_MAX_BRIGHTNESS
#define ORACLE_LEDS_CONFIG_MAX_BRIGHTNESS ORACLE_LEDS_CONFIG_MAX_BRIGHTNESS_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_MAX_BRIGHTNESS */

#ifndef ORACLE_LEDS_CONFIG_MIN_CUBICWAVE
#define ORACLE_LEDS_CONFIG_MIN_CUBICWAVE ORACLE_LEDS_CONFIG_MIN_CUBICWAVE_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_MIN_CUBICWAVE */

#ifndef ORACLE_LEDS_CONFIG_MAX_CUBICWAVE
#define ORACLE_LEDS_CONFIG_MAX_CUBICWAVE ORACLE_LEDS_CONFIG_MAX_CUBICWAVE_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_MAX_CUBICWAVE */

#ifndef ORACLE_LEDS_CONFIG_FADE_AMOUNT
#define ORACLE_LEDS_CONFIG_FADE_AMOUNT ORACLE_LEDS_CONFIG_FADE_AMOUNT_DEFAULT
#endif /* ORACLE_LEDS_CONFIG_FADE_AMOUNT */

/* HCSR04_CONFIG Configuration Varibles*/

#ifndef ORACLE_HCSR04_CONFIG_ECHO_PIN
#define ORACLE_HCSR04_CONFIG_ECHO_PIN ORACLE_HCSR04_CONFIG_ECHO_PIN_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_ECHO_PIN */

#ifndef ORACLE_HCSR04_CONFIG_TRIGGER_PIN
#define ORACLE_HCSR04_CONFIG_TRIGGER_PIN ORACLE_HCSR04_CONFIG_TRIGGER_PIN_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_TRIGGER_PIN */

#ifndef ORACLE_HCSR04_CONFIG_MAX_DISTANCE
#define ORACLE_HCSR04_CONFIG_MAX_DISTANCE ORACLE_HCSR04_CONFIG_MAX_DISTANCE_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_MAX_DISTANCE */

#ifndef ORACLE_HCSR04_CONFIG_MAX_VALUE
#define ORACLE_HCSR04_CONFIG_MAX_VALUE ORACLE_HCSR04_CONFIG_MAX_VALUE_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_MAX_VALUE */

#ifndef ORACLE_HCSR04_CONFIG_EXPECTED_DISTANCE
#define ORACLE_HCSR04_CONFIG_EXPECTED_DISTANCE ORACLE_HCSR04_CONFIG_EXPECTED_DISTANCE_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_EXPECTED_DISTANCE */

#ifndef ORACLE_HCSR04_CONFIG_EXPECTED_DURATION
#define ORACLE_HCSR04_CONFIG_EXPECTED_DURATION ORACLE_HCSR04_CONFIG_EXPECTED_DURATION_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_EXPECTED_DURATION */

#ifndef ORACLE_HCSR04_CONFIG_REPEAT
#define ORACLE_HCSR04_CONFIG_REPEAT ORACLE_HCSR04_CONFIG_REPEAT_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_REPEAT */

#ifndef ORACLE_HCSR04_CONFIG_SPEED_OF_SOUND
#define ORACLE_HCSR04_CONFIG_SPEED_OF_SOUND ORACLE_HCSR04_CONFIG_SPEED_OF_SOUND_DEFAULT
#endif /* ORACLE_HCSR04_CONFIG_SPEED_OF_SOUND */

/* Parfum Configuration Variables */

#ifndef ORACLE_PARFUM_CONFIG_ALWAYS_ON
#define ORACLE_PARFUM_CONFIG_ALWAYS_ON ORACLE_PARFUM_CONFIG_ALWAYS_ON_DEFAULT
#endif /* ORACLE_PARFUM_CONFIG_ALWAYS_ON */

#ifndef ORACLE_PARFUM_CONFIG_PIN
#define ORACLE_PARFUM_CONFIG_PIN ORACLE_PARFUM_CONFIG_PIN_DEFAULT
#endif /* ORACLE_PARFUM_CONFIG_PIN */

#ifndef ORACLE_PARFUM_CONFIG_MAX_TIME
#define ORACLE_PARFUM_CONFIG_MAX_TIME ORACLE_PARFUM_CONFIG_MAX_TIME_DEFAULT
#endif /* ORACLE_PARFUM_CONFIG_MAX_TIME */

/* Papillon Configuration Variables */

#define ORACLE_PAPILLON_CONFIG_SERVO_MAX_NUM ORACLE_PAPILLON_CONFIG_SERVO_MAX_NUM_DEFAULT

#ifndef ORACLE_PAPILLON_CONFIG_SERVO_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO_NUM ORACLE_PAPILLON_CONFIG_SERVO_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO1_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO1_PIN ORACLE_PAPILLON_CONFIG_SERVO1_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO1_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO1_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO1_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO1_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO1_ROUND_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO2_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO2_PIN ORACLE_PAPILLON_CONFIG_SERVO2_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO2_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO2_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO2_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO2_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO2_ROUND_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO3_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO3_PIN ORACLE_PAPILLON_CONFIG_SERVO3_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO3_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO3_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO3_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO3_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO3_ROUND_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO4_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO4_PIN ORACLE_PAPILLON_CONFIG_SERVO4_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO4_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO4_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO4_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO4_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO4_ROUND_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO5_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO5_PIN ORACLE_PAPILLON_CONFIG_SERVO5_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO5_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO5_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO5_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO5_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO5_ROUND_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO6_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO6_PIN ORACLE_PAPILLON_CONFIG_SERVO6_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO6_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO6_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO6_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO6_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO6_ROUND_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO7_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO7_PIN ORACLE_PAPILLON_CONFIG_SERVO7_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO7_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO7_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO7_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO7_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO7_ROUND_NUM */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO8_PIN
#define ORACLE_PAPILLON_CONFIG_SERVO8_PIN ORACLE_PAPILLON_CONFIG_SERVO8_PIN_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO8_PIN */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE ORACLE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE ORACLE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE
#define ORACLE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE ORACLE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE
#endif /* ORACLE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE */

#ifndef ORACLE_PAPILLON_CONFIG_SERVO8_ROUND_NUM
#define ORACLE_PAPILLON_CONFIG_SERVO8_ROUND_NUM ORACLE_PAPILLON_CONFIG_SERVO8_ROUND_NUM_DEFAULT
#endif /* ORACLE_PAPILLON_CONFIG_SERVO8_ROUND_NUM */

#ifndef ORACLE_BUBBLE_CONFIG_ALWAYS_ON
#define ORACLE_BUBBLE_CONFIG_ALWAYS_ON ORACLE_BUBBLE_CONFIG_ALWAYS_ON_DEFAULT
#endif /* ORACLE_BUBBLE_CONFIG_ALWAYS_ON */

#ifndef ORACLE_BUBBLE_CONFIG_STATE_PIN
#define ORACLE_BUBBLE_CONFIG_STATE_PIN ORACLE_BUBBLE_CONFIG_STATE_PIN_DEFAULT
#endif /* ORACLE_BUBBLE_CONFIG_STATE_PIN */

#ifndef ORACLE_BUBBLE_CONFIG_ACTION_PIN
#define ORACLE_BUBBLE_CONFIG_ACTION_PIN ORACLE_BUBBLE_CONFIG_ACTION_PIN_DEFAULT
#endif /* ORACLE_BUBBLE_CONFIG_ACTION_PIN */

#ifndef ORACLE_BUBBLE_CONFIG_MAX_TIME
#define ORACLE_BUBBLE_CONFIG_MAX_TIME ORACLE_BUBBLE_CONFIG_MAX_TIME_DEFAULT
#endif /* ORACLE_BUBBLE_CONFIG_MAX_TIME */

#ifndef ORACLE_BUBBLE_CONFIG_STATE_THRESHOLD
#define ORACLE_BUBBLE_CONFIG_STATE_THRESHOLD ORACLE_BUBBLE_CONFIG_STATE_THRESHOLD_DEFAULT
#endif /* ORACLE_BUBBLE_CONFIG_STATE_THRESHOLD */

#ifndef ORACLE_SMOCK_CONFIG_ALWAYS_ON
#define ORACLE_SMOCK_CONFIG_ALWAYS_ON ORACLE_SMOCK_CONFIG_ALWAYS_ON_DEFAULT
#endif /* ORACLE_SMOCK_CONFIG_ALWAYS_ON */

#ifndef ORACLE_SMOCK_CONFIG_PIN
#define ORACLE_SMOCK_CONFIG_PIN ORACLE_SMOCK_CONFIG_PIN_DEFAULT
#endif /* ORACLE_SMOCK_CONFIG_PIN */

#ifndef ORACLE_SMOCK_CONFIG_MAX_TIME
#define ORACLE_SMOCK_CONFIG_MAX_TIME ORACLE_SMOCK_CONFIG_MAX_TIME_DEFAULT
#endif /* ORACLE_SMOCK_CONFIG_MAX_TIME */

#ifndef ORACLE_SMOCK_CONFIG_MAX_REPEAT
#define ORACLE_SMOCK_CONFIG_MAX_REPEAT ORACLE_SMOCK_CONFIG_MAX_REPEAT_DEFAULT
#endif /* ORACLE_SMOCK_CONFIG_MAX_REPEAT */

#ifndef ORACLE_RC522_CONFIG_SDA_PIN
#define ORACLE_RC522_CONFIG_SDA_PIN ORACLE_RC522_CONFIG_SDA_PIN_DEFAULT
#endif /* ORACLE_RC522_CONFIG_SDA_PIN */

#ifndef ORACLE_RC522_CONFIG_RST_PIN
#define ORACLE_RC522_CONFIG_RST_PIN ORACLE_RC522_CONFIG_RST_PIN_DEFAULT
#endif /* ORACLE_RC522_CONFIG_RST_PIN */

#ifndef ORACLE_RC522_CONFIG_SCK_PIN
#define ORACLE_RC522_CONFIG_SCK_PIN ORACLE_RC522_CONFIG_SCK_PIN_DEFAULT
#endif /* ORACLE_RC522_CONFIG_SCK_PIN */

#ifndef ORACLE_RC522_CONFIG_MOSI_PIN
#define ORACLE_RC522_CONFIG_MOSI_PIN ORACLE_RC522_CONFIG_MOSI_PIN_DEFAULT
#endif /* ORACLE_RC522_CONFIG_MOSI_PIN */

#ifndef ORACLE_RC522_CONFIG_MISO_PIN
#define ORACLE_RC522_CONFIG_MISO_PIN ORACLE_RC522_CONFIG_MISO_PIN_DEFAULT
#endif /* ORACLE_RC522_CONFIG_MISO_PIN */

#endif /* __include_oracle_default_config_h */
