#ifndef AliceDefaultConfig_h
#define AliceDefaultConfig_h

/*****************************************************/
/****************** DEFAULT VALUES *******************/
/*****************************************************/

/* Network Configuration Variables */
#define ALICE_WIFI_CONFIG_SSID_DEFAULT                  "AliceTestSSID"
#define ALICE_WIFI_CONFIG_PWD_DEFAULT                   "AliceTestPWD"
#define ALICE_WIFI_CONFIG_MAC_ADDRESS_DEFAULT           "32:AE:A4:07:0D:66"
#define ALICE_WIFI_CONFIG_FIRST_DELAY_DEFAULT           1000
#define ALICE_WIFI_CONFIG_TIMEOUT_DEFAULT               1000
#define ALICE_WIFI_CONFIG_RETRY_DEFAULT                 1000
#define ALICE_SERVER_CONFIG_PORT_DEFAULT                80   /* default HTTP port */

/* Esp32 Configuration Variables */
#define ALICE_ESP32_CONFIG_NAME_DEFAULT                 "alice_ESP32_test_name"
#define ALICE_ESP32_CONFIG_DELAY_DEFAULT                100

/* Leds Configuration Variables */
#define ALICE_LEDS_CONFIG_NUM_LEDS_DEFAULT              30
#define ALICE_LEDS_CONFIG_LED_PIN_DEFAULT               19
#define ALICE_LEDS_CONFIG_COLOR_ORDER_DEFAULT           GRB
#define ALICE_LEDS_CONFIG_LED_TYPE_DEFAULT              WS2812B
#define ALICE_LEDS_CONFIG_MAX_BRIGHTNESS_DEFAULT        255
#define ALICE_LEDS_CONFIG_MIN_CUBICWAVE_DEFAULT         50
#define ALICE_LEDS_CONFIG_MAX_CUBICWAVE_DEFAULT         90
#define ALICE_LEDS_CONFIG_FADE_AMOUNT_DEFAULT           5

/* HCSR04 Configuration Variables*/
#define ALICE_HCSR04_CONFIG_ECHO_PIN_DEFAULT            18
#define ALICE_HCSR04_CONFIG_TRIGGER_PIN_DEFAULT         5
#define ALICE_HCSR04_CONFIG_MAX_DISTANCE_DEFAULT        50
#define ALICE_HCSR04_CONFIG_EXPECTED_DISTANCE_DEFAULT   20
#define ALICE_HCSR04_CONFIG_EXPECTED_DURATION_DEFAULT   4000
#define ALICE_HCSR04_CONFIG_MAX_VALUE_DEFAULT           5000
#define ALICE_HCSR04_CONFIG_REPEAT_DEFAULT              10
#define ALICE_HCSR04_CONFIG_SPEED_OF_SOUND_DEFAULT      29.1

/* Papillon Configuration Variables */
#define ALICE_PAPILLON_CONFIG_SERVO_MAX_NUM_DEFAULT     8
#define ALICE_PAPILLON_CONFIG_SERVO_NUM_DEFAULT         1
#define ALICE_PAPILLON_CONFIG_SERVO1_PIN_DEFAULT        5
#define ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE_DEFAULT 160
#define ALICE_PAPILLON_CONFIG_SERVO1_ROUND_NUM_DEFAULT  1
#define ALICE_PAPILLON_CONFIG_SERVO2_PIN_DEFAULT        6
#define ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO2_ROUND_NUM_DEFAULT  1
#define ALICE_PAPILLON_CONFIG_SERVO3_PIN_DEFAULT        7
#define ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO3_ROUND_NUM_DEFAULT  1
#define ALICE_PAPILLON_CONFIG_SERVO4_PIN_DEFAULT        8
#define ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO4_ROUND_NUM_DEFAULT  1
#define ALICE_PAPILLON_CONFIG_SERVO5_PIN_DEFAULT        9
#define ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO5_ROUND_NUM_DEFAULT  1
#define ALICE_PAPILLON_CONFIG_SERVO6_PIN_DEFAULT        10
#define ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO6_ROUND_NUM_DEFAULT  1
#define ALICE_PAPILLON_CONFIG_SERVO7_PIN_DEFAULT        11
#define ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO7_ROUND_NUM_DEFAULT  1
#define ALICE_PAPILLON_CONFIG_SERVO8_PIN_DEFAULT        12
#define ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE_DEFAULT  90
#define ALICE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE_DEFAULT  160
#define ALICE_PAPILLON_CONFIG_SERVO8_ROUND_NUM_DEFAULT  1

/* Parfum Configuration Variables */
#define ALICE_PARFUM_CONFIG_ALWAYS_ON_DEFAULT           0
#define ALICE_PARFUM_CONFIG_PIN_DEFAULT                 18
#define ALICE_PARFUM_CONFIG_MAX_TIME_DEFAULT            10000

/* Define BUBBLE Configuration */
#define ALICE_BUBBLE_CONFIG_ALWAYS_ON_DEFAULT           0
#define ALICE_BUBBLE_CONFIG_STATE_PIN_DEFAULT           34
#define ALICE_BUBBLE_CONFIG_ACTION_PIN_DEFAULT          12
#define ALICE_BUBBLE_CONFIG_MAX_TIME_DEFAULT            10000
#define ALICE_BUBBLE_CONFIG_STATE_THRESHOLD_DEFAULT     300

/* Define CHROMIE Configuration */

#define ALICE_CHROMIE_CONFIG_SDA_PIN_DEFAULT            21
#define ALICE_CHROMIE_CONFIG_SCL_PIN_DEFAULT            22
#define ALICE_CHROMIE_CONFIG_MAX_REPEAT_DEFAULT         5
#define ALICE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT        {0x00, 0x00, 0x00, 0x00}
#define ALICE_CHROMIE_CONFIG_COLOR_RED_DEFAULT          ALICE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ALICE_CHROMIE_CONFIG_COLOR_GREEN_DEFAULT        ALICE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ALICE_CHROMIE_CONFIG_COLOR_BLUE_DEFAULT         ALICE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ALICE_CHROMIE_CONFIG_COLOR_YELLOW_DEFAULT       ALICE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ALICE_CHROMIE_CONFIG_COLOR_PURPLE_DEFAULT       ALICE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT
#define ALICE_CHROMIE_CONFIG_COLOR_PINK_DEFAULT         ALICE_CHROMIE_CONFIG_COLOR_DUMMY_DEFAULT

/* Define SMOCK Configuration */
#define ALICE_SMOCK_CONFIG_ALWAYS_ON_DEFAULT            0
#define ALICE_SMOCK_CONFIG_PIN_DEFAULT                  12
#define ALICE_SMOCK_CONFIG_MAX_TIME_DEFAULT             10000
#define ALICE_SMOCK_CONFIG_MAX_REPEAT_DEFAULT           10

/* Define RFID RC522 Configuration */
#define ALICE_RFID_CONFIG_RST_PIN_DEFAULT         22
#define ALICE_RFID_CONFIG_MISO_PIN_DEFAULT        19
#define ALICE_RFID_CONFIG_MOSI_PIN_DEFAULT        23
#define ALICE_RFID_CONFIG_SCK_PIN_DEFAULT         18
#define ALICE_RFID_CONFIG_SDA_PIN_DEFAULT         5

/*****************************************************/
/************ SET VALUES IF NOT DEFINED **************/
/*****************************************************/

/* Network Config Variables */

#ifndef ALICE_WIFI_CONFIG_SSID
#define ALICE_WIFI_CONFIG_SSID ALICE_WIFI_CONFIG_SSID_DEFAULT
#endif /* ALICE_WIFI_CONFIG_SSID */

#ifndef ALICE_WIFI_CONFIG_PWD
#define ALICE_WIFI_CONFIG_PWD ALICE_WIFI_CONFIG_PWD_DEFAULT
#endif /* ALICE_WIFI_CONFIG_PWD */

#ifndef ALICE_WIFI_CONFIG_MAC_ADDRESS
#define ALICE_WIFI_CONFIG_MAC_ADDRESS ALICE_WIFI_CONFIG_MAC_ADDRESS_DEFAULT
#endif /* ALICE_WIFI_CONFIG_MAC_ADDRESS */

#ifndef ALICE_WIFI_CONFIG_FIRST_DELAY
#define ALICE_WIFI_CONFIG_FIRST_DELAY ALICE_WIFI_CONFIG_FIRST_DELAY_DEFAULT
#endif /* ALICE_WIFI_CONFIG_FIRST_DELAY */

#ifndef ALICE_WIFI_CONFIG_TIMEOUT
#define ALICE_WIFI_CONFIG_TIMEOUT ALICE_WIFI_CONFIG_TIMEOUT_DEFAULT
#endif /* ALICE_WIFI_CONFIG_TIMEOUT */

#ifndef ALICE_WIFI_CONFIG_RETRY
#define ALICE_WIFI_CONFIG_RETRY ALICE_WIFI_CONFIG_RETRY_DEFAULT
#endif /* ALICE_WIFI_CONFIG_RETRY */

#ifndef ALICE_SERVER_CONFIG_PORT
#define ALICE_SERVER_CONFIG_PORT ALICE_SERVER_CONFIG_PORT_DEFAULT
#endif /* ALICE_SERVER_CONFIG_PORT */

/* Esp32 Config Variables */

#ifndef ALICE_ESP32_CONFIG_NAME
#define ALICE_ESP32_CONFIG_NAME ALICE_ESP32_CONFIG_NAME_DEFAULT
#endif /* ALICE_ESP32_CONFIG_NAME */

#ifndef ALICE_ESP32_CONFIG_DELAY
#define ALICE_ESP32_CONFIG_DELAY ALICE_ESP32_CONFIG_DELAY_DEFAULT
#endif /* ALICE_ESP32_CONFIG_DELAY */

/* Leds Config Variables */

#ifndef ALICE_LEDS_CONFIG_NUM_LEDS
#define ALICE_LEDS_CONFIG_NUM_LEDS ALICE_LEDS_CONFIG_NUM_LEDS_DEFAULT
#endif /* ALICE_LEDS_CONFIG_NUM_LEDS */

#ifndef ALICE_LEDS_CONFIG_LED_PIN
#define ALICE_LEDS_CONFIG_LED_PIN ALICE_LEDS_CONFIG_LED_PIN_DEFAULT
#endif /* ALICE_LEDS_CONFIG_LED_PIN */

#ifndef ALICE_LEDS_CONFIG_COLOR_ORDER
#define ALICE_LEDS_CONFIG_COLOR_ORDER ALICE_LEDS_CONFIG_COLOR_ORDER_DEFAULT
#endif /* ALICE_LEDS_CONFIG_COLOR_ORDER */

#ifndef ALICE_LEDS_CONFIG_LED_TYPE
#define ALICE_LEDS_CONFIG_LED_TYPE ALICE_LEDS_CONFIG_LED_TYPE_DEFAULT
#endif /* ALICE_LEDS_CONFIG_LED_TYPE */

#ifndef ALICE_LEDS_CONFIG_MAX_BRIGHTNESS
#define ALICE_LEDS_CONFIG_MAX_BRIGHTNESS ALICE_LEDS_CONFIG_MAX_BRIGHTNESS_DEFAULT
#endif /* ALICE_LEDS_CONFIG_MAX_BRIGHTNESS */

#ifndef ALICE_LEDS_CONFIG_MIN_CUBICWAVE
#define ALICE_LEDS_CONFIG_MIN_CUBICWAVE ALICE_LEDS_CONFIG_MIN_CUBICWAVE_DEFAULT
#endif /* ALICE_LEDS_CONFIG_MIN_CUBICWAVE */

#ifndef ALICE_LEDS_CONFIG_MAX_CUBICWAVE
#define ALICE_LEDS_CONFIG_MAX_CUBICWAVE ALICE_LEDS_CONFIG_MAX_CUBICWAVE_DEFAULT
#endif /* ALICE_LEDS_CONFIG_MAX_CUBICWAVE */

#ifndef ALICE_LEDS_CONFIG_FADE_AMOUNT
#define ALICE_LEDS_CONFIG_FADE_AMOUNT ALICE_LEDS_CONFIG_FADE_AMOUNT_DEFAULT
#endif /* ALICE_LEDS_CONFIG_FADE_AMOUNT */

/* HCSR04_CONFIG Configuration Varibles*/

#ifndef ALICE_HCSR04_CONFIG_ECHO_PIN
#define ALICE_HCSR04_CONFIG_ECHO_PIN ALICE_HCSR04_CONFIG_ECHO_PIN_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_ECHO_PIN */

#ifndef ALICE_HCSR04_CONFIG_TRIGGER_PIN
#define ALICE_HCSR04_CONFIG_TRIGGER_PIN ALICE_HCSR04_CONFIG_TRIGGER_PIN_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_TRIGGER_PIN */

#ifndef ALICE_HCSR04_CONFIG_MAX_DISTANCE
#define ALICE_HCSR04_CONFIG_MAX_DISTANCE ALICE_HCSR04_CONFIG_MAX_DISTANCE_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_MAX_DISTANCE */

#ifndef ALICE_HCSR04_CONFIG_MAX_VALUE
#define ALICE_HCSR04_CONFIG_MAX_VALUE ALICE_HCSR04_CONFIG_MAX_VALUE_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_MAX_VALUE */

#ifndef ALICE_HCSR04_CONFIG_EXPECTED_DISTANCE
#define ALICE_HCSR04_CONFIG_EXPECTED_DISTANCE ALICE_HCSR04_CONFIG_EXPECTED_DISTANCE_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_EXPECTED_DISTANCE */

#ifndef ALICE_HCSR04_CONFIG_EXPECTED_DURATION
#define ALICE_HCSR04_CONFIG_EXPECTED_DURATION ALICE_HCSR04_CONFIG_EXPECTED_DURATION_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_EXPECTED_DURATION */

#ifndef ALICE_HCSR04_CONFIG_REPEAT
#define ALICE_HCSR04_CONFIG_REPEAT ALICE_HCSR04_CONFIG_REPEAT_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_REPEAT */

#ifndef ALICE_HCSR04_CONFIG_SPEED_OF_SOUND
#define ALICE_HCSR04_CONFIG_SPEED_OF_SOUND ALICE_HCSR04_CONFIG_SPEED_OF_SOUND_DEFAULT
#endif /* ALICE_HCSR04_CONFIG_SPEED_OF_SOUND */

/* Parfum Configuration Variables */

#ifndef ALICE_PARFUM_CONFIG_ALWAYS_ON
#define ALICE_PARFUM_CONFIG_ALWAYS_ON ALICE_PARFUM_CONFIG_ALWAYS_ON_DEFAULT
#endif /* ALICE_PARFUM_CONFIG_ALWAYS_ON */

#ifndef ALICE_PARFUM_CONFIG_PIN
#define ALICE_PARFUM_CONFIG_PIN ALICE_PARFUM_CONFIG_PIN_DEFAULT
#endif /* ALICE_PARFUM_CONFIG_PIN */

#ifndef ALICE_PARFUM_CONFIG_MAX_TIME
#define ALICE_PARFUM_CONFIG_MAX_TIME ALICE_PARFUM_CONFIG_MAX_TIME_DEFAULT
#endif /* ALICE_PARFUM_CONFIG_MAX_TIME */

/* Papillon Configuration Variables */

#define ALICE_PAPILLON_CONFIG_SERVO_MAX_NUM ALICE_PAPILLON_CONFIG_SERVO_MAX_NUM_DEFAULT

#ifndef ALICE_PAPILLON_CONFIG_SERVO_NUM
#define ALICE_PAPILLON_CONFIG_SERVO_NUM ALICE_PAPILLON_CONFIG_SERVO_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO1_PIN
#define ALICE_PAPILLON_CONFIG_SERVO1_PIN ALICE_PAPILLON_CONFIG_SERVO1_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO1_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO1_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO1_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO1_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO1_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO1_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO1_ROUND_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO2_PIN
#define ALICE_PAPILLON_CONFIG_SERVO2_PIN ALICE_PAPILLON_CONFIG_SERVO2_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO2_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO2_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO2_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO2_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO2_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO2_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO2_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO2_ROUND_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO3_PIN
#define ALICE_PAPILLON_CONFIG_SERVO3_PIN ALICE_PAPILLON_CONFIG_SERVO3_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO3_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO3_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO1_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO3_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO3_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO3_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO3_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO3_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO3_ROUND_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO4_PIN
#define ALICE_PAPILLON_CONFIG_SERVO4_PIN ALICE_PAPILLON_CONFIG_SERVO4_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO4_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO4_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO4_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO4_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO4_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO4_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO4_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO4_ROUND_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO5_PIN
#define ALICE_PAPILLON_CONFIG_SERVO5_PIN ALICE_PAPILLON_CONFIG_SERVO5_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO5_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO5_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO5_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO5_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO5_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO5_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO5_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO5_ROUND_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO6_PIN
#define ALICE_PAPILLON_CONFIG_SERVO6_PIN ALICE_PAPILLON_CONFIG_SERVO6_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO6_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO6_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO6_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO6_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO6_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO6_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO6_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO6_ROUND_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO7_PIN
#define ALICE_PAPILLON_CONFIG_SERVO7_PIN ALICE_PAPILLON_CONFIG_SERVO7_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO7_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO7_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO7_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO7_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO7_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO7_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO7_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO7_ROUND_NUM */

#ifndef ALICE_PAPILLON_CONFIG_SERVO8_PIN
#define ALICE_PAPILLON_CONFIG_SERVO8_PIN ALICE_PAPILLON_CONFIG_SERVO8_PIN_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO8_PIN */

#ifndef ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE ALICE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO8_MAX_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE
#define ALICE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE ALICE_PAPILLON_CONFIG_SERVO8_MIN_ANGLE
#endif /* ALICE_PAPILLON_CONFIG_SERVO8_INIT_ANGLE */

#ifndef ALICE_PAPILLON_CONFIG_SERVO8_ROUND_NUM
#define ALICE_PAPILLON_CONFIG_SERVO8_ROUND_NUM ALICE_PAPILLON_CONFIG_SERVO8_ROUND_NUM_DEFAULT
#endif /* ALICE_PAPILLON_CONFIG_SERVO8_ROUND_NUM */

#ifndef ALICE_BUBBLE_CONFIG_ALWAYS_ON
#define ALICE_BUBBLE_CONFIG_ALWAYS_ON ALICE_BUBBLE_CONFIG_ALWAYS_ON_DEFAULT
#endif /* ALICE_BUBBLE_CONFIG_ALWAYS_ON */

#ifndef ALICE_BUBBLE_CONFIG_STATE_PIN
#define ALICE_BUBBLE_CONFIG_STATE_PIN ALICE_BUBBLE_CONFIG_STATE_PIN_DEFAULT
#endif /* ALICE_BUBBLE_CONFIG_STATE_PIN */

#ifndef ALICE_BUBBLE_CONFIG_ACTION_PIN
#define ALICE_BUBBLE_CONFIG_ACTION_PIN ALICE_BUBBLE_CONFIG_ACTION_PIN_DEFAULT
#endif /* ALICE_BUBBLE_CONFIG_ACTION_PIN */

#ifndef ALICE_BUBBLE_CONFIG_MAX_TIME
#define ALICE_BUBBLE_CONFIG_MAX_TIME ALICE_BUBBLE_CONFIG_MAX_TIME_DEFAULT
#endif /* ALICE_BUBBLE_CONFIG_MAX_TIME */

#ifndef ALICE_BUBBLE_CONFIG_STATE_THRESHOLD
#define ALICE_BUBBLE_CONFIG_STATE_THRESHOLD ALICE_BUBBLE_CONFIG_STATE_THRESHOLD_DEFAULT
#endif /* ALICE_BUBBLE_CONFIG_STATE_THRESHOLD */

#ifndef ALICE_CHROMIE_CONFIG_SDA_PIN
#define ALICE_CHROMIE_CONFIG_SDA_PIN ALICE_CHROMIE_CONFIG_SDA_PIN_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_SDA_PIN */

#ifndef ALICE_CHROMIE_CONFIG_SCL_PIN
#define ALICE_CHROMIE_CONFIG_SCL_PIN ALICE_CHROMIE_CONFIG_SCL_PIN_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_SCL_PIN */

#ifndef ALICE_CHROMIE_CONFIG_COLOR_RED
#define ALICE_CHROMIE_CONFIG_COLOR_RED ALICE_CHROMIE_CONFIG_COLOR_RED_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_COLOR_RED */

#ifndef ALICE_CHROMIE_CONFIG_COLOR_GREEN
#define ALICE_CHROMIE_CONFIG_COLOR_GREEN ALICE_CHROMIE_CONFIG_COLOR_GREEN_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_COLOR_GREEN */

#ifndef ALICE_CHROMIE_CONFIG_COLOR_BLUE
#define ALICE_CHROMIE_CONFIG_COLOR_BLUE ALICE_CHROMIE_CONFIG_COLOR_BLUE_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_COLOR_BLUE */

#ifndef ALICE_CHROMIE_CONFIG_COLOR_YELLOW
#define ALICE_CHROMIE_CONFIG_COLOR_YELLOW ALICE_CHROMIE_CONFIG_COLOR_YELLOW_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_COLOR_YELLOW */

#ifndef ALICE_CHROMIE_CONFIG_COLOR_PURPLE
#define ALICE_CHROMIE_CONFIG_COLOR_PURPLE ALICE_CHROMIE_CONFIG_COLOR_PURPLE_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_COLOR_PURPLE */

#ifndef ALICE_CHROMIE_CONFIG_COLOR_PINK
#define ALICE_CHROMIE_CONFIG_COLOR_PINK ALICE_CHROMIE_CONFIG_COLOR_PINK_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_COLOR_PINK */

#ifndef ALICE_CHROMIE_CONFIG_MAX_REPEAT
#define ALICE_CHROMIE_CONFIG_MAX_REPEAT ALICE_CHROMIE_CONFIG_MAX_REPEAT_DEFAULT
#endif /* ALICE_CHROMIE_CONFIG_MAX_REPEAT */

#ifndef ALICE_SMOCK_CONFIG_ALWAYS_ON
#define ALICE_SMOCK_CONFIG_ALWAYS_ON ALICE_SMOCK_CONFIG_ALWAYS_ON_DEFAULT
#endif /* ALICE_SMOCK_CONFIG_ALWAYS_ON */

#ifndef ALICE_SMOCK_CONFIG_PIN
#define ALICE_SMOCK_CONFIG_PIN ALICE_SMOCK_CONFIG_PIN_DEFAULT
#endif /* ALICE_SMOCK_CONFIG_PIN */

#ifndef ALICE_SMOCK_CONFIG_MAX_TIME
#define ALICE_SMOCK_CONFIG_MAX_TIME ALICE_SMOCK_CONFIG_MAX_TIME_DEFAULT
#endif /* ALICE_SMOCK_CONFIG_MAX_TIME */

#ifndef ALICE_SMOCK_CONFIG_MAX_REPEAT
#define ALICE_SMOCK_CONFIG_MAX_REPEAT ALICE_SMOCK_CONFIG_MAX_REPEAT_DEFAULT
#endif /* ALICE_SMOCK_CONFIG_MAX_REPEAT */

#ifndef ALICE_RFID_CONFIG_SDA_PIN
#define ALICE_RFID_CONFIG_SDA_PIN ALICE_RFID_CONFIG_SDA_PIN_DEFAULT
#endif /* ALICE_RFID_CONFIG_SDA_PIN */

#ifndef ALICE_RFID_CONFIG_RST_PIN
#define ALICE_RFID_CONFIG_RST_PIN ALICE_RFID_CONFIG_RST_PIN_DEFAULT
#endif /* ALICE_RFID_CONFIG_RST_PIN */

#ifndef ALICE_RFID_CONFIG_SCK_PIN
#define ALICE_RFID_CONFIG_SCK_PIN ALICE_RFID_CONFIG_SCK_PIN_DEFAULT
#endif /* ALICE_RFID_CONFIG_SCK_PIN */

#ifndef ALICE_RFID_CONFIG_MOSI_PIN
#define ALICE_RFID_CONFIG_MOSI_PIN ALICE_RFID_CONFIG_MOSI_PIN_DEFAULT
#endif /* ALICE_RFID_CONFIG_MOSI_PIN */

#ifndef ALICE_RFID_CONFIG_MISO_PIN
#define ALICE_RFID_CONFIG_MISO_PIN ALICE_RFID_CONFIG_MISO_PIN_DEFAULT
#endif /* ALICE_RFID_CONFIG_MISO_PIN */

#endif /* AliceDefaultConfig_h */
