
#include <oracle_puppets.h>

static oracle_puppets_context_t oracle_puppets_context;

static const int ORACLE_PUPPETS_PUPPET_init_angle[ORACLE_PUPPETS_NUM_PUPPETS] = {
    ORACLE_PUPPETS_PUPPET1_INIT_ANGLE,
    ORACLE_PUPPETS_PUPPET2_INIT_ANGLE,
    ORACLE_PUPPETS_PUPPET3_INIT_ANGLE,
    ORACLE_PUPPETS_PUPPET4_INIT_ANGLE,
    ORACLE_PUPPETS_PUPPET5_INIT_ANGLE,
    ORACLE_PUPPETS_PUPPET6_INIT_ANGLE,
    ORACLE_PUPPETS_PUPPET7_INIT_ANGLE,
    ORACLE_PUPPETS_PUPPET8_INIT_ANGLE
};

static const int ORACLE_PUPPETS_PUPPET_min_angle[ORACLE_PUPPETS_NUM_PUPPETS] = {
    ORACLE_PUPPETS_PUPPET1_MIN_ANGLE,
    ORACLE_PUPPETS_PUPPET2_MIN_ANGLE,
    ORACLE_PUPPETS_PUPPET3_MIN_ANGLE,
    ORACLE_PUPPETS_PUPPET4_MIN_ANGLE,
    ORACLE_PUPPETS_PUPPET5_MIN_ANGLE,
    ORACLE_PUPPETS_PUPPET6_MIN_ANGLE,
    ORACLE_PUPPETS_PUPPET7_MIN_ANGLE,
    ORACLE_PUPPETS_PUPPET8_MIN_ANGLE
};

static const int ORACLE_PUPPETS_PUPPET_max_angle[ORACLE_PUPPETS_NUM_PUPPETS] = {
    ORACLE_PUPPETS_PUPPET1_MAX_ANGLE,
    ORACLE_PUPPETS_PUPPET2_MAX_ANGLE,
    ORACLE_PUPPETS_PUPPET3_MAX_ANGLE,
    ORACLE_PUPPETS_PUPPET4_MAX_ANGLE,
    ORACLE_PUPPETS_PUPPET5_MAX_ANGLE,
    ORACLE_PUPPETS_PUPPET6_MAX_ANGLE,
    ORACLE_PUPPETS_PUPPET7_MAX_ANGLE,
    ORACLE_PUPPETS_PUPPET8_MAX_ANGLE
};

static const int ORACLE_PUPPETS_PUPPET_gpio_pin[ORACLE_PUPPETS_NUM_PUPPETS] = {
    ORACLE_PUPPETS_PUPPET1_GPIO_PIN,
    ORACLE_PUPPETS_PUPPET2_GPIO_PIN,
    ORACLE_PUPPETS_PUPPET3_GPIO_PIN,
    ORACLE_PUPPETS_PUPPET4_GPIO_PIN,
    ORACLE_PUPPETS_PUPPET5_GPIO_PIN,
    ORACLE_PUPPETS_PUPPET6_GPIO_PIN,
    ORACLE_PUPPETS_PUPPET7_GPIO_PIN,
    ORACLE_PUPPETS_PUPPET8_GPIO_PIN
};

void oracle_puppets_loop(void)
{
    oracle_puppets_context_t *ctx = &oracle_puppets_context;

    for (int i = 0; i < ctx->num_puppets; i++ ) {
        /* Skip inactive motors*/
        if (!ctx->puppets->enable) {
            continue;
        }
    }
}

void oracle_puppets_setup(void)
{
    return;
}